import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
const apiCalls = [];
page.on('response', (r) => { const u = r.url(); if (/\.json|api|doc/i.test(u) && !/gtm|clevertap|google/i.test(u)) apiCalls.push(u); });
await page.goto('https://tripjack.com/page/api-doc', { waitUntil: 'networkidle', timeout: 90000 });
await page.waitForTimeout(6000);
const txt = await page.evaluate(() => document.body.innerText);
console.log('PAGE TEXT LENGTH:', txt.length);
console.log('--- hotel endpoint paths found ---');
const paths = [...new Set(txt.match(/\/hms\/[a-zA-Z0-9/_-]+/g) || [])];
const roomWords = ['roomImages','room_images','amenities','facilities','bed_config','bedConfig','maxGuest','mga','bds','fcs','oprmd','roomContent','room-content','is_hero_image'];
console.log('--- room-content keywords present in doc text ---');
roomWords.forEach(w => { if (txt.includes(w)) console.log('  FOUND:', w); });
console.log(paths.join('\n') || '(none in text)');
const i = txt.indexOf('Static Detail');
const j = txt.indexOf('Instant Booking');
console.log('--- STATIC DETAIL DOC SECTION ---');
console.log(txt.slice(i, j > i ? Math.min(j, i + 9000) : i + 9000));
console.log('--- end section ---');
console.log('--- nav/menu items(skip) ---');
if (false)
console.log(JSON.stringify(await page.evaluate(() => [...document.querySelectorAll('a,li,button')].map(e=>e.innerText.trim()).filter(t=>t&&t.length<60).slice(0,120))));
console.log('--- network json ---');
console.log([...new Set(apiCalls)].slice(0,15).join('\n'));
await page.screenshot({ path: 'doc.png' });
await browser.close();
