export const FaqQuestions = {
  caterers: {
    vendor_type_id: 7,
    vendor_type: "Caterers",
    questions: [
      {
        id: 101,
        text: "What is the price of veg menu for 20 items that includes beverages, food appetizers, main course & desserts items (excluding seafood) for 300 PAX?",
        description: "",
        label: ["Price Per Plate"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 102,
        text: "How many guests can you accomodate in your event space?",
        description: "",
        label: ["Minimum number of guests", "Maximum number of guests"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 103,
        text: "What is the price of non-veg menu for 20 items that includes beverages,, food appetizers, main course & desserts items (including seafood) for 300 PAX?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 10000,
      },
      {
        id: 104,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 105,
        text: "What all menus & catering options do you have?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "North indian/ mughlai",
          "Italian/ european/ continental",
          "Chinese/ thai/ oriental",
          "South indian",
          "Garlic Free/ Onion Free",
          "Live food counters",
          "Chaat & Indian street food",
          "Seafood",
          "Drinks (non-alcoholic)",
        ],
        min: null,
        max: null,
      },
      {
        id: 106,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 107,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 108,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 109,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 110,
        text: "Which year did you/your company professionally start your services ?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 111,
        text: "What is the price range of the veg menu for 300 PAX? (Typically include charges for beverages, food appetizers, main course & dessert items)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹2500 - ₹2999",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 112,
        text: "What is the price range of the non veg menu for 300 PAX? (Typically include charges for beverages, food appetizers, main course & dessert items excluding seafood)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹2500 - ₹2999",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  venues: {
    vendor_type_id: 2,
    vendor_type: "venues",
    questions: [
      {
        id: 201,
        text: "Does your venue allow outside caterers?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 202,
        text: "Does your venue allow outside decorators?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 203,
        text: "Does your venue allow outside DJ?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 204,
        text: "Does your venue allow alcohol from outside?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 205,
        text: "Does your venue allow fireworks?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 206,
        text: "Does your venue have rooms available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 207,
        text: "What are the different spaces available at your venue?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Banquet Hall",
          "Lawn",
          "Resort",
          "Marriage Garden",
          "Mandapam",
          "Palace/ Fort",
          "Destination Wedding Venue",
          "Other",
        ],
        min: null,
        max: null,
      },
      {
        id: 208,
        text: "What is your USP (Unique Selling Proposition)?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 209,
        text: "How many guests can you accommodate?",
        description: "",
        label: ["Minimum number of guests", "Maximum number of guests"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 210,
        text: "Do you provide valet parking?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 211,
        text: "What is the starting price per plate (for veg menu)?",
        description: "",
        label: ["Price Per Plate (Veg)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 212,
        text: "What is the starting price per plate (for non-veg menu)?",
        description: "",
        label: ["Price Per Plate (Non-Veg)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 213,
        text: "What is the rental charge of your venue (if applicable)?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
  preweddingphotography: {
    vendor_type_id: 12,
    vendor_type: "preweddingphotography",
    questions: [
      {
        id: 301,
        text: "How many processed (edited) pictures do you usually deliver to the client?",
        description: "",
        label: [],
        type: "radio",
        options: ["<25", "25-50", "50-100", "100-200"],
        min: null,
        max: null,
      },
      {
        id: 302,
        text: "Which services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Still Photography", "Videography", "Albums"],
        min: null,
        max: null,
      },
      {
        id: 303,
        text: "What are your payment terms?",
        description: "",
        label: [],
        type: "radio",
        options: ["25% Advance", "50% Advance", "100% Advance"],
        min: null,
        max: null,
      },
      {
        id: 304,
        text: "Please mention any awards you have received?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 305,
        text: "Who bears the pre-wedding shoot location cost?",
        description: "",
        label: [],
        type: "radio",
        options: ["Borne by client", "Borne by photographer (Only Local)"],
        min: null,
        max: null,
      },
      {
        id: 306,
        text: "Who bears cost of travel and lodging when travelling to a different city?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Cost of stay and travel borne by client",
          "Cost of stay borne by client and travel by photographer",
          "Both borne by you",
        ],
        min: null,
        max: null,
      },
      {
        id: 307,
        text: "Pricing for Pre-wedding stills? (Per day)",
        description: "",
        label: ["Price per Day (Stills)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 308,
        text: "What are the terms & conditions of your cancellation policy? (Please describe in detail - eg. No refunds within a month of the wedding day or 50% amount refundable)",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 309,
        text: "Who bears the travel and stay cost for outstation weddings?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Cost of stay and travel borne by client",
          "Cost of stay borne by client and travel by you",
          "Both borne by you",
        ],
        min: null,
        max: null,
      },
      {
        id: 310,
        text: "Pricing for Pre-wedding films? (Per day)",
        description: "",
        label: ["Price per Day (Films)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 311,
        text: "How long have you been doing pre-wedding photography?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
  photographer: {
    vendor_type_id: 1,
    vendor_type: "Photographer",
    questions: [
      {
        id: 3101,
        text: "What is the price for 1 day Marriage offering that includes Photography and Videography (Candid/ Cinematographic & Traditional) for an audience size of 300?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples seach by price",
        label: ["1 Day Wedding Package"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 3102,
        text: "What is the price for 1 day pre-wedding photoshoot? (Typically includes: Teaser & a highlight video with photographs shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 3103,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 3104,
        text: "What is the price for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 3105,
        text: "What is the price for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 3106,
        text: "What are the occasions that you cover?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding & engagement",
          "Engagement photography",
          "Mehandi & sangeet",
          "Couple pre-wedding",
          "Parties",
          "Corporate events",
          "Maternity shoot",
          "Baby shoot",
        ],
        min: null,
        max: null,
      },
      {
        id: 3107,
        text: "What shooting capabilities do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Traditional",
          "Candid",
          "Cinematographic",
          "Drone Shoots",
          "Photobooth",
          "Live Screening",
        ],
        min: null,
        max: null,
      },
      {
        id: 3108,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3109,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 3110,
        text: "What is the % advance amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 3111,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 3112,
        text: "Which year did you/your company professionally start services in?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 3113,
        text: "What is the price range for 1 day pre-wedding photoshoot? (Typically includes: Teaser & a highlight video with photographs shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 3114,
        text: "What is the price range for 1 day wedding package for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 3115,
        text: "What is the price range for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 3116,
        text: "What is the price range for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹75,000",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 - ₹3,99,999",
          "₹4,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  florist: {
    vendor_type_id: 13,
    vendor_type: "Florist",
    questions: [
      {
        id: 801,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 802,
        text: "What is the starting price for indoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 803,
        text: "What is the starting price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 804,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 805,
        text: "What is the starting price for outdoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 806,
        text: "What is the starting price for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events? (Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 807,
        text: "Which flowers do you provide for floral decorations?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Jasmine",
          "Sunflower",
          "Lotus",
          "Rose",
          "Orchid",
          "Lillies",
          "Perwinkle",
          "Bougainvillaea",
          "Marigold",
          "Hibiscus",
          "Carnations",
          "Gerbera",
        ],
        min: null,
        max: null,
      },
      {
        id: 808,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 809,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 810,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 811,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 812,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "checkbox",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 813,
        text: "What is the price range for flower based home decoration for sangeet related events? (Typically includes decoration of balcony, entrance, & common area)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹24,999",
          "₹25,000 - ₹29,999",
          "₹30,000 - ₹39,999",
          "₹40,000 - ₹49,999",
          "₹50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 814,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 815,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?(Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  decorators: {
    vendor_type_id: 4,
    vendor_type: "Decorators",
    questions: [
      {
        id: 1201,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1202,
        text: "What is the price for flower based traditional decoration for an outdoor setup for 300 PAX? (Typically includes decoration of entrance, passage, guest area, stage area, manadapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 3000000,
      },
      {
        id: 1203,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1204,
        text: "What all traditional themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Floral",
          "Rajasthani",
          "Punjabi",
          "South indian",
          "Royal",
          "Bollywood",
        ],
        min: null,
        max: null,
      },
      {
        id: 1205,
        text: "What all modern themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Art deco/ Gatsby",
          "Vintage",
          "Bohemian",
          "Greenhouse",
          "Metallic",
          "Moroccan",
          "Rustic",
          "Sun downer",
          "Theatrical",
        ],
        min: null,
        max: null,
      },
      {
        id: 1206,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1207,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1208,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1209,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1210,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1211,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1212,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingDJ: {
    vendor_type_id: 8,
    vendor_type: "Wedding DJ",
    questions: [
      {
        id: 1501,
        text: "What is the starting price for 1 event of your DJ only services?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1502,
        text: "What is the starting price for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 50000,
      },
      {
        id: 1503,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1504,
        text: "Which musical genres do you specialise in?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bollywood",
          "EDM",
          "Punjabi",
          "Rock",
          "Hollywood",
          "Hip-hop",
        ],
        min: null,
        max: null,
      },
      {
        id: 1505,
        text: "What additional setups do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Sound system",
          "Dance floor",
          "Lighting",
          "LED screens",
          "Projector",
          "Karaoke",
        ],
        min: null,
        max: null,
      },
      {
        id: 1506,
        text: "Which forms of payment do you accept",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1507,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1508,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1509,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1510,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1511,
        text: "What is the starting price range for 1 event of your DJ only services?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 5,000",
          "5,000 - 9,999",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 39,999",
          "40,000 - 49,999",
          "50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1512,
        text: "What is the starting price range for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 10,000",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 49,999",
          "50,000 - 74,999",
          "75,000 - 99,999",
          "1,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  pandits: {
    vendor_type_id: 14,
    vendor_type: "Pandits",
    questions: [
      {
        id: 1601,
        text: "What is the starting price for wedding ceremony services (pooja/ feras)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Lowest price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1602,
        text: "What type of pooja/ceremony services do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding ceremony",
          "Kundali match-making",
          "Griha pravesh",
          "Yagya/ Hawan",
          "Mangal dosh",
          "Sundarkand/ Mata ki chowki",
          "Gauri pooja",
          "Lakshmi pooja",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1603,
        text: "What are the languages in which you can perform rituals/ceremonies?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hindi",
          "Sanskrit",
          "Tamil",
          "Telugu",
          "Kannada",
          "Marathi",
          "English",
          "Gujrati",
          "Bangali",
          "Marwari",
          "Jain",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1604,
        text: "How do you provide consultation services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Office/ Shop",
          "Home visit",
          "Online consultation",
          "Telephonic consultation",
          "Video consultation",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1605,
        text: "What religions/ faiths can you serve with ceremony or ritual services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hinduism",
          "Islam",
          "Jainism",
          "Sikhism",
          "Buddhism",
          "Christianity",
          "Parsis",
          "Judaism",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1606,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1607,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1608,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1609,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1610,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1611,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1612,
        text: "What is the starting price range for wedding ceremony services (pooja/ feras)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹19,999",
          "₹20,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  gifts: {
    vendor_type_id: 9,
    vendor_type: "Gifts",
    questions: [
      {
        id: 2101,
        text: "What is the starting price per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price per gift"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2102,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 2103,
        text: "What is the starting price per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 5000,
      },
      {
        id: 2104,
        text: "What is the minimum order quantity for edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2105,
        text: "What is the minimum order quantity for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2106,
        text: "What types of gifting options do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Edible", "Non-edible"],
        min: null,
        max: null,
      },
      {
        id: 2107,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 2108,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2109,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2110,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2111,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2112,
        text: "What is the starting price range per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2113,
        text: "What is the starting price range per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2114,

        text: "What is the minimum order quantity range for edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2115,
        text: "What is the minimum order quantity range for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },

  groomwear: {
    vendor_type_id: 11,
    vendor_type: "groomwear",
    questions: [
      {
        id: 401,
        text: "Which of the following outfit types do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Sherwani",
          "Bandhgala",
          "Indo-western",
          "Achkan",
          "Jodhpuri",
          "Suits & Tuxedos",
          "Kurta Pyjama sets",
        ],
        min: null,
        max: null,
      },
      {
        id: 402,
        text: "Do you provide customization services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 403,
        text: "Which type of collection do you primarily deal in?",
        description: "",
        label: [],
        type: "radio",
        options: ["Men’s Wear", "Couple Outfits"],
        min: null,
        max: null,
      },
      {
        id: 404,
        text: "What is the price range of your outfits?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹24,999",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 405,
        text: "What is the starting price of Sherwanis?",
        description: "",
        label: ["Price (Sherwanis)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 406,
        text: "What is the starting price of Suits/Tuxedos?",
        description: "",
        label: ["Price (Suits/Tuxedos)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 407,
        text: "Do you provide rental outfits?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 408,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
        ],
        min: null,
        max: null,
      },
      {
        id: 409,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 410,
        text: "Which year did you/your store professionally start providing groom wear?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  jewellery: {
    vendor_type_id: 6,
    vendor_type: "jewellery",
    questions: [
      {
        id: 501,
        text: "Which types of jewellery do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Gold Jewellery",
          "Diamond Jewellery",
          "Polki Jewellery",
          "Kundan Jewellery",
          "Platinum Jewellery",
          "Silver Jewellery",
          "Gemstone Jewellery",
          "Temple Jewellery",
          "Antique Jewellery",
          "Artificial/Imitation Jewellery",
        ],
        min: null,
        max: null,
      },
      {
        id: 502,
        text: "Do you provide customised jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 503,
        text: "Do you provide rental jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 504,
        text: "What is the starting price range of your jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹49,999",
          "₹50,000 - ₹99,999",
          "₹1,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹4,99,999",
          "₹5,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 505,
        text: "Do you provide Hallmarked Jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 506,
        text: "Do you provide certification for your jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 507,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 508,
        text: "What is your cancellation/return policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 509,
        text: "Which year did you/your store professionally start providing jewellery?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  bridalwear: {
    vendor_type_id: 10,
    vendor_type: "bridalwear",
    questions: [
      {
        id: 601,
        text: "Which of the following outfit types do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bridal Lehengas",
          "Light Lehengas",
          "Sarees",
          "Shararas",
          "Gowns",
          "Anarkalis",
          "Custom made outfits",
        ],
        min: null,
        max: null,
      },
      {
        id: 602,
        text: "Do you provide customization services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 603,
        text: "Do you provide rental outfits?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 604,
        text: "What is the price range of your outfits?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹24,999",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 605,
        text: "What is the starting price of bridal lehengas?",
        description: "",
        label: ["Price (Bridal Lehengas)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 606,
        text: "What is the starting price of light lehengas?",
        description: "",
        label: ["Price (Light Lehengas)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 607,
        text: "What is the starting price of sarees?",
        description: "",
        label: ["Price (Sarees)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 608,
        text: "What is the starting price of gowns?",
        description: "",
        label: ["Price (Gowns)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 609,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 610,
        text: "What is your cancellation/return policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 611,
        text: "Which year did you/your store professionally start providing bridal wear?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  bridalmakeup: {
    vendor_type_id: 3,
    vendor_type: "bridalmakeup",
    questions: [
      {
        id: 701,
        text: "Which of the following services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bridal Makeup",
          "Party Makeup for family",
          "Engagement Makeup",
          "Airbrush Makeup",
          "HD Makeup",
          "Hair Styling",
          "Draping",
          "Nail Extensions",
          "Eyelashes",
        ],
        min: null,
        max: null,
      },
      {
        id: 702,
        text: "Do you travel to the venue?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 703,
        text: "Do you offer trials?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes (Paid)", "Yes (Free)", "No"],
        min: null,
        max: null,
      },
      {
        id: 704,
        text: "What is the price (per function) for bridal makeup?",
        description: "",
        label: ["Price per Function (Bridal Makeup)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 705,
        text: "What is the price range for party makeup for family?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹7,499",
          "₹7,500 - ₹9,999",
          "₹10,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 706,
        text: "Which brands of makeup do you use?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 707,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
        ],
        min: null,
        max: null,
      },
      {
        id: 708,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 709,
        text: "Which year did you/your team professionally start providing makeup services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
  mehendiartists: {
    vendor_type_id: 5,
    vendor_type: "mehendiartists",
    questions: [
      {
        id: 801,
        text: "Which types of mehendi designs do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Indian",
          "Arabic",
          "Indo-Arabic",
          "Western",
          "Indo-western",
          "Moroccan",
          "Pakistani",
          "Customised designs",
        ],
        min: null,
        max: null,
      },
      {
        id: 802,
        text: "Do you provide home service?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 803,
        text: "What is your starting price for bridal mehendi?",
        description: "",
        label: ["Price (Bridal Mehendi)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 804,
        text: "What is your starting price range for family/guest mehendi?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹1,000",
          "₹1,000 - ₹2,499",
          "₹2,500 - ₹4,999",
          "₹5,000 - ₹7,499",
          "₹7,500 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 805,
        text: "How many mehendi artists are available for events?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 806,
        text: "Do you provide trials?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 807,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 808,
        text: "Which year did you/your team professionally start providing mehendi services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
};
