export const FaqQuestions = {
  caterers: {
    vendor_type_id: 7,
    vendor_type: "Caterers",
    questions: [
      {
        id: 101,
        text: "Veg or non-veg catering?",
        description: "",
        label: [],
        type: "radio",
        options: ["Pure Veg", "Veg + Non-Veg"],
        min: null,
        max: null,
      },
      {
        id: 102,
        text: "Jain food available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 103,
        text: "Custom menu available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 104,
        text: "Live counters available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 105,
        text: "Max guests handled?",
        description: "",
        label: [],
        type: "radio",
        options: ["0-100", "100-300", "300-500", "500-1000", "1000+"],
        min: null,
        max: null,
      },
      {
        id: 106,
        text: "Per plate price?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Below ₹500",
          "₹500-₹1000",
          "₹1000-₹1500",
          "₹1500-₹2500",
          "₹2500+",
        ],
        min: null,
        max: null,
      },
      {
        id: 107,
        text: "Tasting available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 108,
        text: "Serving staff included?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 109,
        text: "Crockery included?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 110,
        text: "Outdoor catering supported?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 111,
        text: "Destination weddings supported?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 112,
        text: "Hygiene standards?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Gloves & Caps",
          "Sanitized Kitchen",
          "Food Safety Certified",
          "FSSAI Licensed",
        ],
        min: null,
        max: null,
      },
      {
        id: 113,
        text: "Advance required?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 114,
        text: "Cancellation policy?",
        description: "",
        label: [],
        type: "radio",
        options: ["Non Refundable", "Partial Refund", "Flexible"],
        min: null,
        max: null,
      },
      {
        id: 115,
        text: "Best known for?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Taste",
          "Presentation",
          "Live Counters",
          "Variety",
          "Budget Catering",
          "Luxury Catering",
        ],
        min: null,
        max: null,
      },
    ],
  },
  venues: {
    vendor_type_id: 2,
    vendor_type: "venues",
    questions: [
      {
        id: 201,
        text: "Outside catering allowed?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 202,
        text: "Jain food available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 203,
        text: "Max capacity?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-100",
          "100-300",
          "300-500",
          "500-1000",
          "1000+",
        ],
        min: null,
        max: null,
      },
      {
        id: 204,
        text: "Parking available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 205,
        text: "Rooms available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 206,
        text: "Alcohol allowed?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 207,
        text: "Decor restrictions?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "In-house Only",
          "Panel Only",
          "Outside Allowed",
          "Both",
          "Other",
        ],
        allowOther: true,
        min: null,
        max: null,
      },
      {
        id: 208,
        text: "DJ allowed?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 209,
        text: "Noise time limit?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "No Restriction",
          "Till 10 PM",
          "Till 12 AM",
          "As per Government Rules",
          "Other",
        ],
        allowOther: true,
        min: null,
        max: null,
      },
      {
        id: 210,
        text: "Power backup available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Full", "Partial", "None"],
        min: null,
        max: null,
      },
      {
        id: 211,
        text: "Wheelchair accessible?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 212,
        text: "Bridal room available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 213,
        text: "Outside vendors allowed?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "All Vendors Allowed",
          "Selected Vendors Only",
          "Not Allowed",
        ],
        min: null,
        max: null,
      },
      {
        id: 214,
        text: "Advance required?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 215,
        text: "Cancellation policy?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Non Refundable",
          "Partial Refund",
          "Flexible",
          "Other",
        ],
        allowOther: true,
        min: null,
        max: null,
      },
    ],
  },
  preweddingphotography: {
    vendor_type_id: 12,
    vendor_type: "preweddingphotography",
    questions: [
      {
        id: 301,
        text: "How many processed (edited) pictures do you usually deliver to the client?",
        description: "",
        label: [],
        type: "radio",
        options: ["<25", "25-50", "50-100", "100-200"],
        min: null,
        max: null,
      },
      {
        id: 302,
        text: "Which services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Still Photography", "Videography", "Albums"],
        min: null,
        max: null,
      },
      {
        id: 303,
        text: "What are your payment terms?",
        description: "",
        label: [],
        type: "radio",
        options: ["25% Advance", "50% Advance", "100% Advance"],
        min: null,
        max: null,
      },
      {
        id: 304,
        text: "Please mention any awards you have received?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 305,
        text: "Who bears the pre-wedding shoot location cost?",
        description: "",
        label: [],
        type: "radio",
        options: ["Borne by client", "Borne by photographer (Only Local)"],
        min: null,
        max: null,
      },
      {
        id: 306,
        text: "Who bears cost of travel and lodging when travelling to a different city?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Cost of stay and travel borne by client",
          "Cost of stay borne by client and travel by photographer",
          "Both borne by you",
        ],
        min: null,
        max: null,
      },
      {
        id: 307,
        text: "Pricing for Pre-wedding stills? (Per day)",
        description: "",
        label: ["Price per Day (Stills)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 308,
        text: "What are the terms & conditions of your cancellation policy? (Please describe in detail - eg. No refunds within a month of the wedding day or 50% amount refundable)",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 309,
        text: "Who bears the travel and stay cost for outstation weddings?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Cost of stay and travel borne by client",
          "Cost of stay borne by client and travel by you",
          "Both borne by you",
        ],
        min: null,
        max: null,
      },
      {
        id: 310,
        text: "Pricing for Pre-wedding films? (Per day)",
        description: "",
        label: ["Price per Day (Films)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 311,
        text: "How long have you been doing pre-wedding photography?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      { id: 351, text: "Do you provide pre-wedding photoshoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 352, text: "Do you offer cinematic video shoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 353, text: "Is drone shooting available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 354, text: "Do you help with shoot concepts?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 355, text: "Is travel included in your package?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 356, text: "Can I get reels for Instagram?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 357, text: "Do you provide raw images?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 358, text: "Is same-day shoot possible?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 359, text: "Do you offer destination shoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 360, text: "Can I get edited photos within 7 days?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 361, text: "Do you provide outfit guidance?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 362, text: "Is advance booking required?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 363, text: "Do you shoot in 4K video?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 364, text: "Can you handle multi-day shoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 365, text: "Do you provide full shoot packages (photo + video)?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  preweddinglocation: {
    vendor_type_id: 12,
    vendor_type: "Pre Wedding Shoot Location",
    subcategory_keyword: "location",
    questions: [
      { id: 371, text: "Is photography allowed at the location?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 372, text: "Is drone shooting permitted?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 373, text: "Are changing rooms available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 374, text: "Is the location private for shoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 375, text: "Can I book location for half day?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 376, text: "Are props available at the location?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 377, text: "Is power supply available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 378, text: "Is advance booking required?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 379, text: "Is parking available on-site?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 380, text: "Can large crews (10+ people) shoot here?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 381, text: "Is makeup room available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 382, text: "Is the location suitable for sunset shoots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 383, text: "Are permits included in pricing?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 384, text: "Is indoor shooting available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 385, text: "Is the location accessible by car?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  photographer: {
    vendor_type_id: 1,
    vendor_type: "Photographer",
    questions: [
      {
        id: 3101,
        text: "Do you provide candid photography?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3102,
        text: "Do you cover pre-wedding shoots?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3103,
        text: "Do you travel outside city?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3104,
        text: "Drone shoot available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3105,
        text: "How many photos delivered?",
        description: "",
        label: [],
        type: "radio",
        options: ["100-300", "300-500", "500-1000", "1000+"],
        min: null,
        max: null,
      },
      {
        id: 3106,
        text: "Delivery time?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "7 Days",
          "15 Days",
          "30 Days",
          "45+ Days",
        ],
        min: null,
        max: null,
      },
      {
        id: 3107,
        text: "Raw files provided?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3108,
        text: "Album included?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3109,
        text: "Team size?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Solo",
          "2-3 Members",
          "4-6 Members",
          "6+ Members",
        ],
        min: null,
        max: null,
      },
      {
        id: 3110,
        text: "Female photographer available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3111,
        text: "Backup team available?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3112,
        text: "Advance required?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 3113,
        text: "Cancellation policy?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Non Refundable",
          "Partial Refund",
          "Flexible",
        ],
        min: null,
        max: null,
      },
      {
        id: 3114,
        text: "Editing style?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Light & Airy",
          "Dark & Moody",
          "Vibrant",
          "Natural Tone",
          "Matte Finish",
        ],
        min: null,
        max: null,
      },
      {
        id: 3115,
        text: "Best suited for?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Couple Shoots",
          "Big Weddings",
          "Intimate Weddings",
          "Destination Weddings",
        ],
        min: null,
        max: null,
      },
    ],
  },
  florist: {
    vendor_type_id: 13,
    vendor_type: "Florist",
    questions: [
      {
        id: 801,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 802,
        text: "What is the starting price for indoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 803,
        text: "What is the starting price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 804,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 805,
        text: "What is the starting price for outdoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 806,
        text: "What is the starting price for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events? (Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 807,
        text: "Which flowers do you provide for floral decorations?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Jasmine",
          "Sunflower",
          "Lotus",
          "Rose",
          "Orchid",
          "Lillies",
          "Perwinkle",
          "Bougainvillaea",
          "Marigold",
          "Hibiscus",
          "Carnations",
          "Gerbera",
        ],
        min: null,
        max: null,
      },
      {
        id: 808,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 809,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 810,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 811,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 812,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 813,
        text: "What is the price range for flower based home decoration for sangeet related events? (Typically includes decoration of balcony, entrance, & common area)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹24,999",
          "₹25,000 - ₹29,999",
          "₹30,000 - ₹39,999",
          "₹40,000 - ₹49,999",
          "₹50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 814,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 815,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?(Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
      { id: 851, text: "Do you provide fresh flowers?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 852, text: "Do you handle wedding floral decor?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 853, text: "Is same-day delivery available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 854, text: "Do you provide bridal bouquets?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 855, text: "Are exotic/imported flowers available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 856, text: "Do you offer bulk flower supply?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 857, text: "Is customization available for arrangements?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 858, text: "Do you provide flower garlands (var mala)?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 859, text: "Is setup included for events?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 860, text: "Do you provide car decoration flowers?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 861, text: "Are preserved flowers available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 862, text: "Is delivery included in pricing?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 863, text: "Do you offer eco-friendly flower options?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 864, text: "Can you handle large wedding orders?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 865, text: "Do you provide premium packaging options?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  decorators: {
    vendor_type_id: 4,
    vendor_type: "Decorators",
    questions: [
      {
        id: 1201,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1202,
        text: "What is the price for flower based traditional decoration for an outdoor setup for 300 PAX? (Typically includes decoration of entrance, passage, guest area, stage area, manadapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 3000000,
      },
      {
        id: 1203,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1204,
        text: "What all traditional themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Floral",
          "Rajasthani",
          "Punjabi",
          "South indian",
          "Royal",
          "Bollywood",
        ],
        min: null,
        max: null,
      },
      {
        id: 1205,
        text: "What all modern themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Art deco/ Gatsby",
          "Vintage",
          "Bohemian",
          "Greenhouse",
          "Metallic",
          "Moroccan",
          "Rustic",
          "Sun downer",
          "Theatrical",
        ],
        min: null,
        max: null,
      },
      {
        id: 1206,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1207,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1208,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1209,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1210,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1211,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1212,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingDJ: {
    vendor_type_id: 8,
    vendor_type: "Wedding DJ",
    subcategory_keyword: "dj",
    questions: [
      {
        id: 1501,
        text: "What is the starting price for 1 event of your DJ only services?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1502,
        text: "What is the starting price for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 50000,
      },
      {
        id: 1503,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1504,
        text: "Which musical genres do you specialise in?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bollywood",
          "EDM",
          "Punjabi",
          "Rock",
          "Hollywood",
          "Hip-hop",
        ],
        min: null,
        max: null,
      },
      {
        id: 1505,
        text: "What additional setups do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Sound system",
          "Dance floor",
          "Lighting",
          "LED screens",
          "Projector",
          "Karaoke",
        ],
        min: null,
        max: null,
      },
      {
        id: 1506,
        text: "Which forms of payment do you accept",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1507,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1508,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1509,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1510,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1511,
        text: "What is the starting price range for 1 event of your DJ only services?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 5,000",
          "5,000 - 9,999",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 39,999",
          "40,000 - 49,999",
          "50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1512,
        text: "What is the starting price range for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 10,000",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 49,999",
          "50,000 - 74,999",
          "75,000 - 99,999",
          "1,00,000 and more",
        ],
        min: null,
        max: null,
      },
      { id: 1551, text: "Can DJ handle 500+ guests?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1552, text: "Does DJ provide sound system?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1553, text: "Does DJ provide lighting setup?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1554, text: "Can DJ sync music with bride/groom entry?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1555, text: "Can DJ create custom playlists?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1556, text: "Does DJ take live song requests?", type: "radio", options: ["Yes", "No", "Limited"], min: null, max: null },
      { id: 1557, text: "Is DJ suitable for baraat?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1558, text: "Does DJ travel outside city?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1559, text: "Are special effects like CO2 / pyros available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1560, text: "Does DJ bring backup equipment?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1561, text: "Can DJ handle multiple events same day?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1562, text: "Is DJ suitable for high-energy sangeet nights?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1563, text: "Can DJ integrate with live performers?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1564, text: "Does DJ require generator backup?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1565, text: "Is DJ beginner / intermediate / expert level?", type: "radio", options: ["Beginner", "Intermediate", "Expert"], min: null, max: null },
    ],
  },
  sangeetchoreographer: {
    vendor_type_id: 8,
    vendor_type: "Sangeet Choreographers",
    subcategory_keyword: "choreographer",
    questions: [
      {
        id: 1591,
        text: "What is the starting price for 1 sangeet choreography package?",
        description: "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1592,
        text: "What dance styles do you specialise in?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Bollywood", "Semi-Classical", "Hip-Hop", "Contemporary", "Bhangra", "Garba / Dandiya", "Fusion", "Freestyle"],
        min: null,
        max: null,
      },
      {
        id: 1593,
        text: "What is the rehearsal mode you offer?",
        description: "",
        label: [],
        type: "radio",
        options: ["In-person only", "Online only", "Both (Hybrid)"],
        min: null,
        max: null,
      },
      {
        id: 1594,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Cash", "Cheque/ DD", "Credit/ Debit card", "UPI", "Net Banking", "Mobile wallets"],
        min: null,
        max: null,
      },
      {
        id: 1595,
        text: "What is the % payment / amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1596,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1597,
        text: "Which year did you / your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1598,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1599,
        text: "What is the starting price range for 1 sangeet choreography package?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 5,000",
          "5,000 - 9,999",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 49,999",
          "50,000 and more",
        ],
        min: null,
        max: null,
      },
      { id: 1571, text: "Can choreographer handle non-dancers?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1572, text: "Does choreographer teach kids and seniors?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1573, text: "Can they choreograph couple performances?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1574, text: "Is music editing included?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1575, text: "Are rehearsal sessions flexible?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1576, text: "Can rehearsals be done online?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1577, text: "Will choreographer be present on event day?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1578, text: "Can they create story-based performances?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1579, text: "Do they provide assistants?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1580, text: "Can they handle large groups (20+)?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1581, text: "Are props included in choreography?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1582, text: "Do they help with costumes?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1583, text: "Is last-minute choreography possible?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1584, text: "Can they handle multiple performances in one event?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1585, text: "Is choreography beginner-friendly?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  weddingentertainer: {
    vendor_type_id: 8,
    vendor_type: "Wedding Entertainment",
    subcategory_keyword: "entertainer",
    questions: [
      {
        id: 1721,
        text: "What is the starting price for 1 event of your entertainment services?",
        description: "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1722,
        text: "What type of performer are you?",
        description: "",
        label: [],
        type: "radio",
        options: ["Magician", "Live Band", "Singer", "Instrumentalist", "Stand-up Comedian", "Dance Troupe", "Fire Performer", "LED Performer", "Other"],
        min: null,
        max: null,
      },
      {
        id: 1723,
        text: "What event types do you cover?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Sangeet", "Cocktail", "Reception", "Mehendi", "Haldi", "Baraat", "After Party", "Kids Party"],
        min: null,
        max: null,
      },
      {
        id: 1724,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Cash", "Cheque/ DD", "Credit/ Debit card", "UPI", "Net Banking", "Mobile wallets"],
        min: null,
        max: null,
      },
      {
        id: 1725,
        text: "What is the % payment / amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1726,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1727,
        text: "Which year did you / your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1728,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1729,
        text: "What is the starting price range for 1 event of your entertainment services?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 5,000",
          "5,000 - 9,999",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 49,999",
          "50,000 - 99,999",
          "1,00,000 and more",
        ],
        min: null,
        max: null,
      },
      { id: 1701, text: "Is entertainer suitable for kids?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1702, text: "Can entertainer engage large crowds (300+)?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1703, text: "Is performance interactive?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1704, text: "Does entertainer require stage setup?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1705, text: "Does entertainer provide own equipment?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1706, text: "Can performance be customized?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1707, text: "Is entertainer suitable for cocktail events?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1708, text: "Can entertainer perform multiple slots?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1709, text: "Is this a high-energy act?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1710, text: "Does entertainer travel outside city?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1711, text: "Is sound system required from client?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1712, text: "Can entertainer handle mixed audience?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1713, text: "Are costume changes included?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1714, text: "Is performance suitable for outdoor venues?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1715, text: "Can entertainer handle last-minute bookings?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  pandits: {
    vendor_type_id: 14,
    vendor_type: "Pandits",
    questions: [
      {
        id: 1601,
        text: "What is the starting price for wedding ceremony services (pooja/ feras)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Lowest price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1602,
        text: "What type of pooja/ceremony services do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding ceremony",
          "Kundali match-making",
          "Griha pravesh",
          "Yagya/ Hawan",
          "Mangal dosh",
          "Sundarkand/ Mata ki chowki",
          "Gauri pooja",
          "Lakshmi pooja",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1603,
        text: "What are the languages in which you can perform rituals/ceremonies?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hindi",
          "Sanskrit",
          "Tamil",
          "Telugu",
          "Kannada",
          "Marathi",
          "English",
          "Gujrati",
          "Bangali",
          "Marwari",
          "Jain",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1604,
        text: "How do you provide consultation services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Office/ Shop",
          "Home visit",
          "Online consultation",
          "Telephonic consultation",
          "Video consultation",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1605,
        text: "What religions/ faiths can you serve with ceremony or ritual services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hinduism",
          "Islam",
          "Jainism",
          "Sikhism",
          "Buddhism",
          "Christianity",
          "Parsis",
          "Judaism",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1606,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1607,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1608,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1609,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1610,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1611,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1612,
        text: "What is the starting price range for wedding ceremony services (pooja/ feras)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹19,999",
          "₹20,000 and more",
        ],
        min: null,
        max: null,
      },
      { id: 1651, text: "Do you perform full wedding rituals?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1652, text: "Do you provide pooja samagri?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1653, text: "Can you conduct destination weddings?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1654, text: "Do you explain rituals during ceremony?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1655, text: "Is kundli matching available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1656, text: "Can rituals be customized based on family traditions?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1657, text: "Do you perform interfaith weddings?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1658, text: "Is havan included in ceremony?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1659, text: "Do you provide assistant pandits?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1660, text: "Is advance booking required?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1661, text: "Can ceremony be conducted in regional language?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1662, text: "Do you travel outstation for weddings?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1663, text: "Is same-day booking possible?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1664, text: "Do you provide muhurat guidance?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 1665, text: "Is microphone/audio setup required?", type: "radio", options: ["Yes", "No"], min: null, max: null },
    ],
  },
  gifts: {
    vendor_type_id: 9,
    vendor_type: "Gifts",
    questions: [
      {
        id: 2101,
        text: "What is the starting price per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price per gift"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2102,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 2103,
        text: "What is the starting price per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 5000,
      },
      {
        id: 2104,
        text: "What is the minimum order quantity for edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2105,
        text: "What is the minimum order quantity for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2106,
        text: "What types of gifting options do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Edible", "Non-edible"],
        min: null,
        max: null,
      },
      {
        id: 2107,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 2108,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2109,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2110,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2111,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2112,
        text: "What is the starting price range per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2113,
        text: "What is the starting price range per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2114,

        text: "What is the minimum order quantity range for edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2115,
        text: "What is the minimum order quantity range for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },

  groomwear: {
    vendor_type_id: 11,
    vendor_type: "groomwear",
    questions: [
      {
        id: 401,
        text: "Which of the following outfit types do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Sherwani",
          "Bandhgala",
          "Indo-western",
          "Achkan",
          "Jodhpuri",
          "Suits & Tuxedos",
          "Kurta Pyjama sets",
        ],
        min: null,
        max: null,
      },
      {
        id: 402,
        text: "Do you provide customization services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 403,
        text: "Which type of collection do you primarily deal in?",
        description: "",
        label: [],
        type: "radio",
        options: ["Men’s Wear", "Couple Outfits"],
        min: null,
        max: null,
      },
      {
        id: 404,
        text: "What is the price range of your outfits?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹24,999",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 405,
        text: "What is the starting price of Sherwanis?",
        description: "",
        label: ["Price (Sherwanis)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 406,
        text: "What is the starting price of Suits/Tuxedos?",
        description: "",
        label: ["Price (Suits/Tuxedos)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 407,
        text: "Do you provide rental outfits?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 408,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
        ],
        min: null,
        max: null,
      },
      {
        id: 409,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 410,
        text: "Which year did you/your store professionally start providing groom wear?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  jewellery: {
    vendor_type_id: 6,
    vendor_type: "jewellery",
    questions: [
      {
        id: 501,
        text: "Which types of jewellery do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Gold Jewellery",
          "Diamond Jewellery",
          "Polki Jewellery",
          "Kundan Jewellery",
          "Platinum Jewellery",
          "Silver Jewellery",
          "Gemstone Jewellery",
          "Temple Jewellery",
          "Antique Jewellery",
          "Artificial/Imitation Jewellery",
        ],
        min: null,
        max: null,
      },
      {
        id: 502,
        text: "Do you provide customised jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 503,
        text: "Do you provide rental jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 504,
        text: "What is the starting price range of your jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹49,999",
          "₹50,000 - ₹99,999",
          "₹1,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹4,99,999",
          "₹5,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 505,
        text: "Do you provide Hallmarked Jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 506,
        text: "Do you provide certification for your jewellery?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 507,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 508,
        text: "What is your cancellation/return policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 509,
        text: "Which year did you/your store professionally start providing jewellery?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  bridalwear: {
    vendor_type_id: 10,
    vendor_type: "bridalwear",
    questions: [
      {
        id: 601,
        text: "Which of the following outfit types do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bridal Lehengas",
          "Light Lehengas",
          "Sarees",
          "Shararas",
          "Gowns",
          "Anarkalis",
          "Custom made outfits",
        ],
        min: null,
        max: null,
      },
      {
        id: 602,
        text: "Do you provide customization services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 603,
        text: "Do you provide rental outfits?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 604,
        text: "What is the price range of your outfits?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,000",
          "₹10,000 - ₹24,999",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 605,
        text: "What is the starting price of bridal lehengas?",
        description: "",
        label: ["Price (Bridal Lehengas)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 606,
        text: "What is the starting price of light lehengas?",
        description: "",
        label: ["Price (Light Lehengas)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 607,
        text: "What is the starting price of sarees?",
        description: "",
        label: ["Price (Sarees)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 608,
        text: "What is the starting price of gowns?",
        description: "",
        label: ["Price (Gowns)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 609,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 610,
        text: "What is your cancellation/return policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 611,
        text: "Which year did you/your store professionally start providing bridal wear?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },

  bridalmakeup: {
    vendor_type_id: 3,
    vendor_type: "bridalmakeup",
    questions: [
      {
        id: 701,
        text: "Which of the following services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bridal Makeup",
          "Party Makeup for family",
          "Engagement Makeup",
          "Airbrush Makeup",
          "HD Makeup",
          "Hair Styling",
          "Draping",
          "Nail Extensions",
          "Eyelashes",
        ],
        min: null,
        max: null,
      },
      {
        id: 702,
        text: "Do you travel to the venue?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 703,
        text: "Do you offer trials?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes (Paid)", "Yes (Free)", "No"],
        min: null,
        max: null,
      },
      {
        id: 704,
        text: "What is the price (per function) for bridal makeup?",
        description: "",
        label: ["Price per Function (Bridal Makeup)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 705,
        text: "What is the price range for party makeup for family?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹7,499",
          "₹7,500 - ₹9,999",
          "₹10,000 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 706,
        text: "Which brands of makeup do you use?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 707,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
        ],
        min: null,
        max: null,
      },
      {
        id: 708,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 709,
        text: "Which year did you/your team professionally start providing makeup services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
  mehendiartists: {
    vendor_type_id: 5,
    vendor_type: "mehendiartists",
    questions: [
      {
        id: 801,
        text: "Which types of mehendi designs do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Indian",
          "Arabic",
          "Indo-Arabic",
          "Western",
          "Indo-western",
          "Moroccan",
          "Pakistani",
          "Customised designs",
        ],
        min: null,
        max: null,
      },
      {
        id: 802,
        text: "Do you provide home service?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 803,
        text: "What is your starting price for bridal mehendi?",
        description: "",
        label: ["Price (Bridal Mehendi)"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 804,
        text: "What is your starting price range for family/guest mehendi?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹1,000",
          "₹1,000 - ₹2,499",
          "₹2,500 - ₹4,999",
          "₹5,000 - ₹7,499",
          "₹7,500 and above",
        ],
        min: null,
        max: null,
      },
      {
        id: 805,
        text: "How many mehendi artists are available for events?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 806,
        text: "Do you provide trials?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 807,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 808,
        text: "Which year did you/your team professionally start providing mehendi services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      { id: 871, text: "Do you provide bridal mehendi?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 872, text: "Guest mehendi available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 873, text: "Max guests covered?", type: "radio", options: ["Up to 20", "20–50", "50–100", "100+"], min: null, max: null },
      { id: 874, text: "Mehendi type used?", type: "radio", options: ["Natural Henna", "Organic Henna", "Chemical-Based"], min: null, max: null },
      { id: 875, text: "Custom designs available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 876, text: "Portrait mehendi available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 877, text: "Bridal coverage type?", type: "radio", options: ["Hands Only", "Hands + Feet", "Full Arms + Feet"], min: null, max: null },
      { id: 878, text: "Duration required?", type: "radio", options: ["2–4 Hours", "4–6 Hours", "6–8 Hours", "8+ Hours"], min: null, max: null },
      { id: 879, text: "Color guarantee?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 880, text: "Aftercare instructions provided?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 881, text: "Travel available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 882, text: "Team available?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 883, text: "Pricing model?", type: "radio", options: ["Per Hand", "Per Hour", "Package Based"], min: null, max: null },
      { id: 884, text: "Advance required?", type: "radio", options: ["Yes", "No"], min: null, max: null },
      { id: 885, text: "Cancellation policy?", type: "radio", options: ["Non Refundable", "Partial Refund", "Flexible"], min: null, max: null },
    ],
  },
};
