export const FaqQuestions = {
  caterers: {
    vendor_type_id: 15,
    vendor_type: "Caterers",
    questions: [
      {
        id: 101,
        text: "What is the price of veg menu for 20 items that includes beverages, food appetizers, main course & desserts items (excluding seafood) for 300 PAX?",
        description: "",
        label: ["Price Per Plate"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 102,
        text: "How many guests can you accomodate in your event space?",
        description: "",
        label: ["Minimum number of guests", "Maximum number of guests"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 103,
        text: "What is the price of non-veg menu for 20 items that includes beverages,, food appetizers, main course & desserts items (including seafood) for 300 PAX?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 10000,
      },
      {
        id: 104,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 105,
        text: "What all menus & catering options do you have?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "North indian/ mughlai",
          "Italian/ european/ continental",
          "Chinese/ thai/ oriental",
          "South indian",
          "Garlic Free/ Onion Free",
          "Live food counters",
          "Chaat & Indian street food",
          "Seafood",
          "Drinks (non-alcoholic)",
        ],
        min: null,
        max: null,
      },
      {
        id: 106,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 107,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 108,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 109,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 110,
        text: "Which year did you/your company professionally start your services ?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 111,
        text: "What is the price range of the veg menu for 300 PAX? (Typically include charges for beverages, food appetizers, main course & dessert items)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹2500 - ₹2999",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 112,
        text: "What is the price range of the non veg menu for 300 PAX? (Typically include charges for beverages, food appetizers, main course & dessert items excluding seafood)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹2500 - ₹2999",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingInvitation: {
    vendor_type_id: 8,
    vendor_type: "Wedding Invitation",
    questions: [
      {
        id: 201,
        text: "What is the starting price per invite for wedding cards?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Perice per invite"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 202,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 203,
        text: "What is the starting price per box for packaged (boxed) invitations?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000,
      },
      {
        id: 204,
        text: "What is the minimum order quantity for printed cards?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 500,
      },
      {
        id: 205,
        text: "What is the minimum order quantity for boxed invites?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 500,
      },
      {
        id: 206,
        text: "What kind of invitation concepts do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Card", "Boxed gifting", "Novel concepts"],
        min: null,
        max: null,
      },
      {
        id: 207,
        text: "What types of papers do you use for print invites?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Matte",
          "Glossy",
          "Handmade",
          "Mylar",
          "Recycled",
          "Parchment",
        ],
        min: null,
        max: null,
      },
      {
        id: 208,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 209,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 210,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 211,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 212,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 213,
        text: "What is the starting price range per invite for wedding cards?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "₹0 - ₹49",
          "₹50 - ₹74",
          "₹75 - ₹99",
          "₹100 - ₹149",
          "₹150 - ₹199",
          "₹200 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 214,
        text: "What is the starting price range per invite for packaged (boxed) invitations only?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "₹0 - ₹99",
          "₹100 - ₹199",
          "₹200 - ₹299",
          "₹300 - ₹499",
          "₹500 - ₹799",
          "₹800 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 215,
        text: "What is the minimum order quantity range for printed cards?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0 - 24",
          "25 - 49",
          "50 - 74",
          "75 - 99",
          "100 - 124",
          "125 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 216,
        text: "What is the minimum order quantity range for packged (boxed) invitations?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0 - 24",
          "25 - 49",
          "50 - 74",
          "75 - 99",
          "100 - 124",
          "125 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  photographer: {
    vendor_type_id: 1,
    vendor_type: "Photographer",
    questions: [
      {
        id: 301,
        text: "What is the price for 1 day Marriage offering that includes Photography and Videography (Candid/ Cinematographic & Traditional) for an audience size of 300?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples seach by price",
        label: ["1 Day Wedding Package"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 302,
        text: "What is the price for 1 day pre-wedding photoshoot? (Typically includes: Teaser & a highlight video with photographs shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 303,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 304,
        text: "What is the price for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 305,
        text: "What is the price for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 306,
        text: "What are the occasions that you cover?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding & engagement",
          "Engagement photography",
          "Mehandi & sangeet",
          "Couple pre-wedding",
          "Parties",
          "Corporate events",
          "Maternity shoot",
          "Baby shoot",
        ],
        min: null,
        max: null,
      },
      {
        id: 307,
        text: "What shooting capabilities do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Traditional",
          "Candid",
          "Cinematographic",
          "Drone Shoots",
          "Photobooth",
          "Live Screening",
        ],
        min: null,
        max: null,
      },
      {
        id: 308,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 309,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 310,
        text: "What is the % advance amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 311,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 312,
        text: "Which year did you/your company professionally start services in?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 313,
        text: "What is the price range for 1 day pre-wedding photoshoot? (Typically includes: Teaser & a highlight video with photographs shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 314,
        text: "What is the price range for 1 day wedding package for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 315,
        text: "What is the price range for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 316,
        text: "What is the price range for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300? (Typically includes: Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹75,000",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 - ₹3,99,999",
          "₹4,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingMusic: {
    vendor_type_id: 4,
    vendor_type: "Wedding Music",
    questions: [
      {
        id: 401,
        text: "What is the starting price per event/ performance?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 402,
        text: "Which types of entertainment services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Anchors & MCs",
          "Live singers",
          "Dancers",
          "Ghazal singers",
          "Karaoke",
          "Shehnai",
          "Stand-up comedy",
          "Bands/ Gigs",
          "Theatre artists",
          "International performers",
          "Celebrity artists",
          "Fireworks",
          "Jugglery arts",
          "Table games",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 403,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 404,
        text: "Do you travel outstation for your services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 405,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 406,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 407,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 408,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 409,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 410,
        text: "What is the starting price range for 1 day performance? (Typically includes: Live singing/ dance/ magic/ stand up performances)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹29,999",
          "₹30,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  transportation: {
    vendor_type_id: 5,
    vendor_type: "Transportation",
    questions: [
      {
        id: 501,
        text: "What is the starting price for 1 day for a seven seating car/Innova for to & fro transportation within the city of booking?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price",
        label: ["Lowest Price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 502,
        text: "What is the starting price for 1 day deluxe non-ac bus for to & fro transportation within the city of booking? (Typically includes charge for 35-50 PAX)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 50000,
      },
      {
        id: 503,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 504,
        text: "What types of vehicles do you have?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "AC buses",
          "Non-AC buses",
          "Volvo",
          "Innova",
          "Tempo travelers",
          "Sedans",
        ],
        min: null,
        max: null,
      },
      {
        id: 505,
        text: "Do you provide vehicles for interstate requests?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 506,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 507,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 508,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 509,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 510,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 511,
        text: "What is the starting price range for 1 day seven seating car/Innova for to & fro transportation within the city of booking?",
        description: "",
        label: [],
        type: "radio",
        options: ["Under ₹1,000", "₹1,000 - 1,499", "₹1,500 and more"],
        min: null,
        max: null,
      },
      {
        id: 512,
        text: "What is the starting price range for 1 day deluxe non-ac bus for to & fro transportation within the city of booking? (Typically includes charge for 35-50 PAX)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹19,999",
          "₹20,000 - ₹29,999",
          "₹30,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  tentHouse: {
    vendor_type_id: 6,
    vendor_type: "Tent House",
    questions: [
      {
        id: 601,
        text: "What is the starting price for an outdoor tent setup for 100 PAX for pre-wedding/community functions? (Typically includes charges for: tent, floor carpet, lighting and seating furniture)",
        description: "",
        label: ["Tent Setup"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 602,
        text: "What is the starting price for indoor tenting services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 500000,
      },
      {
        id: 603,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 604,
        text: "What is the starting price for outdoor tenting services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 605,
        text: "What is the starting price for an outdoor wedding/ reception tent setup for 300 PAX? (Typically includes charges for: tent, floor carpet, lighting, seating furniture and food setup)",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 606,
        text: "What all services can you offer?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 607,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 608,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 609,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 610,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 611,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 612,
        text: "What is the starting price range for a home tent setup for 30 PAX for sangeet related events? (Typically includes charges for: tent, floor carpet,furniture, home exterior tent decoration)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹24,999",
          "₹25,000 - ₹29,999",
          "₹30,000 - ₹39,999",
          "₹40,000 - ₹49,999",
          "₹50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 613,
        text: "What is the starting price range for an outdoor tent setup for 100 PAX for pre-wedding/ community functions? (Typically includes charges for: tent, floor carpet, lighting and seating furniture)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 614,
        text: "What is the starting price range for an outdoor wedding/ reception tent setup for 300 PAX? (Typically includes charges for: tent, floor carpet, lighting, seating furniture and food setup)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  entertainment: {
    vendor_type_id: 7,
    vendor_type: "Entertainment",
    questions: [
      {
        id: 701,
        text: "What is the starting price per event/ performance?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price per event"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 702,
        text: "Which types of entertainment services do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Anchors & MCs",
          "Live singers",
          "Dancers",
          "Ghazal singers",
          "Karaoke",
          "Shehnai",
          "Stand-up comedy",
          "Bands/ Gigs",
          "Theatre artists",
          "International performers",
          "Celebrity artists",
          "Fireworks",
          "Jugglery arts",
          "Table games",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 703,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 704,
        text: "Do you travel outstation for your services?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 705,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 706,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 707,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 708,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 709,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 710,
        text: "What is the starting price range for 1 day performance? (Typically includes: Live singing/ dance/ magic/ stand up performances)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹29,999",
          "₹30,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  florist: {
    vendor_type_id: 21,
    vendor_type: "Florist",
    questions: [
      {
        id: 801,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 802,
        text: "What is the starting price for indoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 803,
        text: "What is the starting price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of: entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 804,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 805,
        text: "What is the starting price for outdoor floral decor services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 806,
        text: "What is the starting price for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events? (Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 2000000,
      },
      {
        id: 807,
        text: "Which flowers do you provide for floral decorations?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Jasmine",
          "Sunflower",
          "Lotus",
          "Rose",
          "Orchid",
          "Lillies",
          "Perwinkle",
          "Bougainvillaea",
          "Marigold",
          "Hibiscus",
          "Carnations",
          "Gerbera",
        ],
        min: null,
        max: null,
      },
      {
        id: 808,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 809,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 810,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 811,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 812,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "checkbox",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 813,
        text: "What is the price range for flower based home decoration for sangeet related events? (Typically includes decoration of balcony, entrance, & common area)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5,000",
          "₹5,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹24,999",
          "₹25,000 - ₹29,999",
          "₹30,000 - ₹39,999",
          "₹40,000 - ₹49,999",
          "₹50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 814,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 815,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?(Typically includes decoration of: entrance, passage, guest area, stage area, mandapa)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingPlanner: {
    vendor_type_id: 12,
    vendor_type: "Weddingplanner",
    questions: [
      {
        id: 901,
        text: "What is the price of your fixed planning fee?",
        description:
          "ENter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Planning fee"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 902,
        text: "What is the minimum wedding budget that the customer should have to avail your services?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 10000000,
      },
      {
        id: 903,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 904,
        text: "In or near which all locations in India do you provide planning services? (Typically includes locations where atleast 3 events per location were organised)",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Jaipur",
          "Goa",
          "Jodhpur",
          "Udaipur",
          "Mumbai",
          "Delhi NCR",
          "Kerala",
          "Hyderabad",
          "Bengaluru",
          "Chennai",
          "Uttarkhand(Massourie/ Nanital)",
          "Himachal(Shimla/ Manali)",
          "Mahabalipuram",
          "Lucknow",
          "Agra",
          "Amritsar",
          "Pune/ Lonavala",
          "Andaman & nicobar",
        ],
        min: null,
        max: null,
      },
      {
        id: 905,
        text: "In which all international locations do you provide planning services? (Typically includes locations where atleast 3 events per location were organised)",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Thailand",
          "Dubai/ UAE",
          "Bali",
          "Malaysia",
          "Mauritius",
          "Sri Lanka",
          "Turkey",
          "Maldives",
          "France",
          "Australia",
          "Spain",
          "Itely",
          "Vietnam",
          "Austria",
          "Greece",
        ],
        min: null,
        max: null,
      },
      {
        id: 906,
        text: "What all specific planning services can you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Venue selection",
          "Catering",
          "Photography/ Videography",
          "Styling & grooming",
          "Decoration",
          "DJ & entertainment",
          "Guest transfers",
          "Hospitality & guests support",
          "Invitations",
          "Wedding cake",
          "Trousseau packing",
          "Band & baraat",
        ],
        min: null,
        max: null,
      },
      {
        id: 907,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 908,
        text: "What is the % advance payment to confirm your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 909,
        text: "What is the cancellation policy of your services?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 910,
        text: "Which year did you/your company professionally start services in?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 911,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 912,
        text: "What is the price range of your fixed planning fee?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - 2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 - ₹3,99,999",
          "₹4,00,000 - ₹4,99,999",
          "₹5,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 913,
        text: "What is the minimum wedding budget range that the customer should have to avail your services?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹10,00,000",
          "₹10,00,000 - ₹14,99,999",
          "₹15,00,000 - ₹19,99,999",
          "₹20,00,000 - ₹24,99,999",
          "₹25,00,000 - 29,99,999",
          "₹30,00,000 - ₹39,99,999",
          "₹40,00,000 - ₹59,99,999",
          "₹60,00,000 - ₹99,99,999",
          "₹1,00,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  videographer: {
    vendor_type_id: 10,
    vendor_type: "Videographer",
    questions: [
      {
        id: 1001,
        text: "What is the price for 1 day wedding package for an audience size of 300? (Typically includes Photography & Videography, both shot candidly and traditionally)",
        description:
          "Enter your average pricing in order for your Storefront to appear in result when couples search by price",
        label: ["1 Day Wedding Package"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1002,
        text: "What is the price for 1 day pre-wedding photoshoot?(Typically includes Teaser & a highlight video with photographs shot candidly and traditionaly)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 1003,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with spaecial deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1004,
        text: "What is the price for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300?(Typically includes Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 1005,
        text: "What is the price for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300? (Typically includes Photography & Videography, both shot candidly and traditionally)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 1000000,
      },
      {
        id: 1006,
        text: "What are the occasions that you cover?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding & engagement",
          "Engagement photography",
          "Mehandi & Sangeet",
          "Couple pre-wedding",
          "Perties",
          "Corporate events",
          "Maternity shoot",
          "Baby shoot",
        ],
        min: null,
        max: null,
      },
      {
        id: 1007,
        text: "What shooting capabilities do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Traditional",
          "Candid",
          "Cinematographic",
          "Drone Shoots",
          "Photobooth",
          "Live Screening",
        ],
        min: null,
        max: null,
      },
      {
        id: 1008,
        text: "Do you travel outside?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1009,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1010,
        text: "What is the % advance amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1011,
        text: "What is your cancellation policy?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1012,
        text: "Which year did you/your company professionally start services in?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1013,
        text: "What is the price range for 1 day pre-wedding photoshoot?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1014,
        text: "What is the price range for 1 day wedding package for an audience size of 300?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1015,
        text: "What is the price range for 2 day wedding package that covers engagement/reception & wedding for an audience size of 300?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - 2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1016,
        text: "What is the price range for 3 day wedding package that covers pre-Wedding, engagement/reception & wedding for an audience size of 300?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹75,000",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,49,999",
          "₹2,50,000 - ₹2,99,999",
          "₹3,00,000 - ₹3,99,999",
          "₹4,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  honeymoon: {
    vendor_type_id: 16,
    vendor_type: "Honeymoon",
    questions: [
      {
        id: 1101,
        text: "What is the starting price for your services?",
        description:
          "Enter your avearge pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Lowest Price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1102,
        text: "What is the starting price per person for honeymoon packages within India?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1103,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1104,
        text: "What is the starting price per person for honeymoon packages for international travel?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1105,
        text: "What are the national destinations where you can provide honeymoon package?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Andamans",
          "Goa",
          "Srinagar",
          "Agra",
          "Sikkim",
          "Kerala",
          "Udaipur",
          "Manali",
          "Dalhousie",
          "Shimla",
          "Kasauli",
          "Coorg",
          "Pondicherry",
          "Darjeeling",
          "Ooty",
          "Shillong",
          "Lakshadweep",
          "Leh & Ladakh",
          "Mahabaleshawar",
          "Lanavala & Khandala",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1106,
        text: "What are the international destinations where you can provide honeymoon package?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Mauritius",
          "Singapore",
          "Malaysia",
          "Thailand",
          "Bali",
          "Maldives",
          "Dubali/ UAE",
          "Sri Lanka",
          "Switzerland",
          "Paris",
          "Prague",
          "Budapest",
          "Vietnam",
          "New Zealand",
          "Italy",
          "USA",
          "Turkey",
          "South Africa",
          "Australia",
          "Greece",
          "Egypt",
          "Spain",
          "Canada",
          "Portugal",
          "UK",
          "Mexico",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1107,
        text: "What all travel package booking services can you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "VISA",
          "Ticketing",
          "Acommodation",
          "Rental cars",
          "Transfers",
          "Adventure activities",
          "Sightseeing",
          "Cruise packages",
          "Religious/ Piligrimage visits",
        ],
        min: null,
        max: null,
      },
      {
        id: 1108,
        text: "What type of holidays does your company specialise in?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1109,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1110,
        text: "What are the popular honeymoon destinations you specialise in?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1111,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1112,
        text: "What all services do you help the couple book?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Accommodation",
          "Flights",
          "Local transportation & transfers",
          "Sight-seeing tours",
          "Other",
        ],
        min: null,
        max: null,
      },
      {
        id: 1113,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1114,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1115,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
    ],
  },
  decorators: {
    vendor_type_id: 12,
    vendor_type: "Decorators",
    questions: [
      {
        id: 1201,
        text: "What is the price for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Venue decor"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1202,
        text: "What is the price for flower based traditional decoration for an outdoor setup for 300 PAX? (Typically includes decoration of entrance, passage, guest area, stage area, manadapa)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 3000000,
      },
      {
        id: 1203,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1204,
        text: "What all traditional themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Floral",
          "Rajasthani",
          "Punjabi",
          "South indian",
          "Royal",
          "Bollywood",
        ],
        min: null,
        max: null,
      },
      {
        id: 1205,
        text: "What all modern themes of decoration can you fulfill?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Art deco/ Gatsby",
          "Vintage",
          "Bohemian",
          "Greenhouse",
          "Metallic",
          "Moroccan",
          "Rustic",
          "Sun downer",
          "Theatrical",
        ],
        min: null,
        max: null,
      },
      {
        id: 1206,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1207,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1208,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1209,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1210,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1211,
        text: "What is the price range for flower based traditional decoration for an indoor venue setup for 100 PAX for pre-wedding/ reception events? (Typically includes decoration of entrance-8x8 ft, passage, guest area, stage area-16x12 ft)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹25,000",
          "₹25,000 - ₹49,999",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1212,
        text: "What is the price range for flower based traditional decoration for an outdoor setup for 300 PAX for wedding events?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹50,000",
          "₹50,000 - ₹74,999",
          "₹75,000 - ₹99,999",
          "₹1,00,000 - ₹1,24,999",
          "₹1,25,000 - ₹1,49,999",
          "₹1,50,000 - ₹1,74,999",
          "₹1,75,000 - ₹1,99,999",
          "₹2,00,000 - ₹2,99,999",
          "₹3,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  cake: {
    vendor_type_id: 19,
    vendor_type: "Cake",
    questions: [
      {
        id: 1301,
        text: "What is the starting price per Kg for a non-tiered cake?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price Per Kg"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1302,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1303,
        text: "Do you provide multi-tier cakes?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1304,
        text: "Which all icing types do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Fondant",
          "Royal",
          "Buttercream",
          "Marzipan",
          "Whipped cream",
          "Hand finished",
        ],
        min: null,
        max: null,
      },
      {
        id: 1305,
        text: "What all shapes of cakes do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Round",
          "Heart",
          "Square",
          "Pillow",
          "Topsy-Turvy",
          "Scalloped",
        ],
        min: null,
        max: null,
      },
      {
        id: 1306,
        text: "What additional products do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cupcakes",
          "Cookies",
          "Brownies",
          "Macarons",
          "Cake pops",
          "Cake jars",
        ],
        min: null,
        max: null,
      },
      {
        id: 1307,
        text: "What types of cake preparations do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Eggless",
          "Suger-free",
          "Gluten-free",
          "Diabetic-friendly",
          "Lactose-free",
          "Vegan",
        ],
        min: null,
        max: null,
      },
      {
        id: 1308,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1309,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1310,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1311,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1312,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1313,
        text: "What is the starting price range per Kg for a non-tiered cake?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 500",
          "500 - 999",
          "1,000 - 1,499",
          "1,500 - 1,999",
          "2,000 - 2,499",
          "2,500 - 2,999",
          "3,000 - 3,999",
          "4,000 - 4,999",
          "5,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  detective: {
    vendor_type_id: 14,
    vendor_type: "Detective",
    questions: [
      {
        id: 1401,
        text: "What is the starting price for your services?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Lowest Price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1402,
        text: "What is included in the pricing?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1403,
        text: "What type of services do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Pre-Matrimonial Check",
          "Divorce Case",
          "Family Case Investigation",
          "Cheating Case Investigation",
          "Other",
        ],
        min: null,
        max: null,
      },
      {
        id: 1404,
        text: "How much time do you take to submit reports?",
        description: "",
        label: [],
        type: "radio",
        options: ["1 week", "15 days", "Other"],
        min: null,
        max: null,
      },
    ],
  },
  weddingDJ: {
    vendor_type_id: 7,
    vendor_type: "Wedding DJ",
    questions: [
      {
        id: 1501,
        text: "What is the starting price for 1 event of your DJ only services?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1502,
        text: "What is the starting price for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 50000,
      },
      {
        id: 1503,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1504,
        text: "Which musical genres do you specialise in?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bollywood",
          "EDM",
          "Punjabi",
          "Rock",
          "Hollywood",
          "Hip-hop",
        ],
        min: null,
        max: null,
      },
      {
        id: 1505,
        text: "What additional setups do you offer?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Sound system",
          "Dance floor",
          "Lighting",
          "LED screens",
          "Projector",
          "Karaoke",
        ],
        min: null,
        max: null,
      },
      {
        id: 1506,
        text: "Which forms of payment do you accept",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1507,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1508,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1509,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1510,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1511,
        text: "What is the starting price range for 1 event of your DJ only services?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 5,000",
          "5,000 - 9,999",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 39,999",
          "40,000 - 49,999",
          "50,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1512,
        text: "What is the starting price range for 1 event of your DJ services with setup? (Typically includes: sound, light & dance floor set up)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under 10,000",
          "10,000 - 14,999",
          "15,000 - 19,999",
          "20,000 - 24,999",
          "25,000 - 29,999",
          "30,000 - 49,999",
          "50,000 - 74,999",
          "75,000 - 99,999",
          "1,00,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  pandits: {
    vendor_type_id: 13,
    vendor_type: "Pandits",
    questions: [
      {
        id: 1601,
        text: "What is the starting price for wedding ceremony services (pooja/ feras)?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Lowest price"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1602,
        text: "What type of pooja/ceremony services do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Wedding ceremony",
          "Kundali match-making",
          "Griha pravesh",
          "Yagya/ Hawan",
          "Mangal dosh",
          "Sundarkand/ Mata ki chowki",
          "Gauri pooja",
          "Lakshmi pooja",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1603,
        text: "What are the languages in which you can perform rituals/ceremonies?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hindi",
          "Sanskrit",
          "Tamil",
          "Telugu",
          "Kannada",
          "Marathi",
          "English",
          "Gujrati",
          "Bangali",
          "Marwari",
          "Jain",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1604,
        text: "How do you provide consultation services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Office/ Shop",
          "Home visit",
          "Online consultation",
          "Telephonic consultation",
          "Video consultation",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1605,
        text: "What religions/ faiths can you serve with ceremony or ritual services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hinduism",
          "Islam",
          "Jainism",
          "Sikhism",
          "Buddhism",
          "Christianity",
          "Parsis",
          "Judaism",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1606,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1607,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1608,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1609,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1610,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1611,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1612,
        text: "What is the starting price range for wedding ceremony services (pooja/ feras)?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹19,999",
          "₹20,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  photobooth: {
    vendor_type_id: 17,
    vendor_type: "Photobooth",
    questions: [
      {
        id: 1701,
        text: "What is the starting price of your photobooth installation for one event?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price per event"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1702,
        text: "What are the types of photobooths that you have?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Vehicle theme",
          "Stand-up board",
          "Hanging props",
          "Speech bubbles",
          "Regional themes",
          "Chalkboard",
          "Love story theme",
          "Aerial shots",
          "Wedding hashtag",
          "Floral",
          "Instagram both",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1703,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with spaecial deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1704,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1705,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1706,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1707,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1708,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1709,
        text: "What is the starting price range of your photobooth installation for one event?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹5000",
          "₹5000 - ₹9999",
          "₹10,000 - ₹14,999",
          "₹15,000 - ₹19,999",
          "₹20,000 - ₹29,999",
          "₹30,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  astrologer: {
    vendor_type_id: 18,
    vendor_type: "Astrologer",
    questions: [
      {
        id: 1801,
        text: "What is the starting price for a session of relationship advice?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price Per Session"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1802,
        text: "What are the astrology services that you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Vedic Astrology",
          "Kundali milan",
          "Palmistry",
          "Relationship advice",
          "Numerology",
          "Vastu shastra",
          "Color therapy",
          "Tantra",
          "Tarot card",
          "Feng shui",
          "Career advice",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1803,
        text: "What are the languages in which you can provide astrology services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Hindi",
          "Sanskrit",
          "Tamil",
          "Telugu",
          "Kannada",
          "Marathi",
          "English",
          "Gujrati",
          "Bangali",
          "Marwari",
          "Odia/Odiya",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1804,
        text: "How do you provide consultation services?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Office/ Shop",
          "Home visit",
          "Online consultation",
          "Telephonic consultation",
          "Video consultation",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1805,
        text: "Do you travel outstation?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1806,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1807,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1808,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1809,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1810,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1811,
        text: "What is the starting price range for a session of relationship advice?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  partyplaces: {
    vendor_type_id: 19,
    vendor_type: "Partyplaces",
    questions: [
      {
        id: 1901,
        text: "What is the starting price per head for an IMFL veg menu?(Typically includes 10 items comprising beverages, food appetizers, main course & desert items, excluding seafood for 30-50 PAX)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price Per Person"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1902,
        text: "What is the starting price per head for an IMFL non-veg menu?(Typically includes 10 items comprising beverages, food appetizers, main course & desert items, excluding seafood for 30-50 PAX)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 20000,
      },
      {
        id: 1903,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 1904,
        text: "What all menus & catering options do you have?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "North indian/ mughlai",
          "Italian/ european/ continental",
          "Chinease/ thai/ oriental",
          "South indian",
          "Garlic Free/ Onion Free",
          "Live food counters",
          "Chaat & indian street food",
          "Seafood",
          "Drinks(non-alcoholic)",
        ],
        min: null,
        max: null,
      },
      {
        id: 1905,
        text: "What are the occasions that your venue is suitable for?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bachelor/bachelorette",
          "Engagement",
          "Cocktail",
          "Reception",
          "Youngsters party",
          "Pool party",
          "Birthday party",
          "Corporate party",
          "Kitty party",
          "Anniversary",
          "Baby shower",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1906,
        text: "How would you describe your party event space?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Pub",
          "Hotel bar",
          "Sports bar",
          "Nightclub",
          "Lounge",
          "Resto-bar",
          "Fine dining",
          "Casual dining",
          "Family restaurant",
          "Cafe",
          "Buffet",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 1907,
        text: "Do you provide imported alcohol packages?",
        description: "",
        label: [],
        type: "radio",
        options: ["Yes", "No"],
        min: null,
        max: null,
      },
      {
        id: 1908,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 1909,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1910,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1911,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1912,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 1913,
        text: "What is the guest range that your venue can accommodate?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "0-24",
          "25-49",
          "50-74",
          "75-99",
          "100-149",
          "150-199",
          "200-299",
          "300-399",
          "400 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1914,
        text: "What is the starting price range per head for an IMFL veg menu?(Typically includes 10 items comprising beverages, food appetizers, main course & desert items, excluding seafood for 30-50 PAX)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 1915,
        text: "What is the starting price range per head for an IMFL non-veg menu?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹500",
          "₹500 - ₹799",
          "₹800 - ₹1199",
          "₹1200 - ₹1499",
          "₹1500 - ₹1799",
          "₹1800 - ₹1999",
          "₹2000 - ₹2499",
          "₹3000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  weddingchoreographer: {
    vendor_type_id: 20,
    vendor_type: "Weddingchoreographer",
    questions: [
      {
        id: 2001,
        text: "What is the starting price per performance for couple dance?",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Per Couple Dance"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2002,
        text: "What is the starting price per performance for family/friends dance? (Typically includes charges for up to 5 performance)",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 10000,
      },
      {
        id: 2003,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 2004,
        text: "What all dance forms can you choreography?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Bollywood",
          "Punjabi",
          "Classical",
          "Old hindi songs",
          "Ball dance",
          "Flash mobs",
          "Contemporary",
          "Hip-hop",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 2005,
        text: "Where do you provide training sessions?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Studio",
          "Client site",
          "Flexible",
          "Online sessions",
          "Recorded sessions",
          "Others",
        ],
        min: null,
        max: null,
      },
      {
        id: 2006,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 2007,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2008,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2009,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2010,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2011,
        text: "What is the starting price range per performance for couple dance? (Typically includes charges for up to 5 minutes performance including 2-3 songs mixed)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2012,
        text: "What is the starting price range per performance for family/friends dance?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹2,000",
          "₹2,000 - ₹4,999",
          "₹5,000 - ₹7,999",
          "₹8,000 - ₹9,999",
          "₹10,000 - ₹14,999",
          "₹15,000 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
  gifts: {
    vendor_type_id: 8,
    vendor_type: "Gifts",
    questions: [
      {
        id: 2101,
        text: "What is the starting price per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description:
          "Enter your average pricing in order for your Storefront to appear in results when couples search by price.",
        label: ["Price per gift"],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2102,
        text: "Are you ready to host/provide service to events during COVID19, following the government guidelines?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Information not available",
          "Not operational",
          "Yes, with special deals",
          "Yes",
        ],
        min: null,
        max: null,
      },
      {
        id: 2103,
        text: "What is the starting price per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "range",
        options: [],
        min: 0,
        max: 5000,
      },
      {
        id: 2104,
        text: "What is the minimum order quantity for edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2105,
        text: "What is the minimum order quantity for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2106,
        text: "What types of gifting options do you provide?",
        description: "",
        label: [],
        type: "checkbox",
        options: ["Edible", "Non-edible"],
        min: null,
        max: null,
      },
      {
        id: 2107,
        text: "Which forms of payment do you accept?",
        description: "",
        label: [],
        type: "checkbox",
        options: [
          "Cash",
          "Cheque/ DD",
          "Credit/ Debit card",
          "UPI",
          "Net Banking",
          "Mobile wallets",
        ],
        min: null,
        max: null,
      },
      {
        id: 2108,
        text: "What is the % payment/ amount to confirm the booking?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2109,
        text: "What is the cancellation policy?",
        description: "",
        label: [],
        type: "text",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2110,
        text: "Which year did you/your company professionally start your services?",
        description: "",
        label: [],
        type: "number",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2111,
        text: "Awards, recognitions and publications",
        description: "",
        label: [],
        type: "textarea",
        options: [],
        min: null,
        max: null,
      },
      {
        id: 2112,
        text: "What is the starting price range per kg for edible gifting or favors? (Typically includes: Sweets or chocolates)",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2113,
        text: "What is the starting price range per gift/ pack for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "Under ₹100",
          "₹100 - ₹199",
          "₹200 - ₹499",
          "₹500 - ₹999",
          "₹1000 - ₹1999",
          "₹2000 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2114,

        text: "What is the minimum order quantity range for edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
      {
        id: 2115,
        text: "What is the minimum order quantity range for non-edible gifting or favors?",
        description: "",
        label: [],
        type: "radio",
        options: [
          "0-19",
          "20-49",
          "50-99",
          "100-199",
          "200-299",
          "300 and more",
        ],
        min: null,
        max: null,
      },
    ],
  },
};
